name: mustaqim
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cherry_toast: ^1.11.0
  cloud_firestore:
  firebase_core: 
  firebase_storage: 
  flutter:
    sdk: flutter
  google_fonts: 
  image_picker: 
  random_string: ^2.3.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

